#!/usr/bin/env bash

find . -type f | while read line; do
  basename=$(basename "$line")
  target="$PWD/$basename"

  if [[ $1 == "mv" ]]; then
    mv -f "$line" "$target"
  elif [[ $1 == "cp" ]]; then
    cp -f "$line" "$target"
  else
    echo "'$line' -> '$target'"
  fi
done
